name: Flake checks
on: [pull_request]

jobs:
  check:
    runs-on: fast-self-hosted
    steps:
      - name: Check out repository code
        uses: https://code.forgejo.org/actions/checkout@v4

      - name: Run flake checks
        run: |
          set -exuo pipefail
          # Prevent cache garbage collection by creating GC roots
          mkdir -p ${HOME}/.local/state/nix/results

          # 1 eval-worker needs about 13GB of memory
          nix --accept-flake-config \
            --access-tokens '' develop \
            --command nix-fast-build \
            --no-nom \
            --skip-cached \
            --systems "x86_64-linux" \
            --eval-workers 2 \
            --max-jobs 20 \
            --out-link ${HOME}/.local/state/nix/results/nix-fast-build
