name: Flake checks
on: [push]

jobs:
  formatting:
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: https://code.forgejo.org/actions/checkout@v4

      - name: Check formatting
        run: |
          nix --accept-flake-config --access-tokens '' develop --command treefmt --ci
